services:

    eight.label:
        class: Eight\PageBundle\Variable\Label
        tags:
            - { name: eight_page.variable }

    eight.text:
        class: Eight\PageBundle\Variable\Text
        tags:
            - { name: eight_page.variable }

    eight.entity:
        class: Eight\PageBundle\Variable\Entity
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.collection:
        class: Eight\PageBundle\Variable\Collection
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.collection_method:
        class: Eight\PageBundle\Variable\CollectionMethod
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.url:
        class: Eight\PageBundle\Variable\Url
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.i18n_url:
        class: Eight\PageBundle\Variable\i18nUrl
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.icon:
        class: Eight\PageBundle\Variable\Icon
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.image:
        class: Eight\PageBundle\Variable\Image
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: eight_page.variable }

    eight.checkbox:
        class: Eight\PageBundle\Variable\Checkbox
        tags:
            - { name: eight_page.variable }

    eight.choices:
        class: Eight\PageBundle\Variable\Choices
        tags:
            - { name: eight_page.variable }

    eight.multiple_labels:
        class: Eight\PageBundle\Variable\MultipleLabels
        tags:
            - { name: eight_page.variable }

